name: Publish to PyPI 📦

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.7.17
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install setuptools wheel twine
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
