name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths:
      - snirf/**
      - tests/**
  pull_request:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt pytest pytest-cov
          pip install --no-build-isolation -ve .
      - run: pytest tests/test.py
      - uses: codecov/codecov-action@v3
        if: success()
